### ISSUE TITLE
Javascript with Razor syntax - Bug

### ISSUE THREAD

**Issue by matmiranda** [madskristensen/JavaScriptRegions#1]
Not work in VS 2017:

```
<script type="text/javascript">

//#region Main

var MyClient = @Html.Raw(Json.Serialize(Model.Client));

//#endregion

</script>
```

**Comment by EikeBierman** [comment]
is it planned to fix that ?

**Comment by madskristensen** [comment]
Outlining doesn't work in `<script>` blocks when Razor is mixed in. This extension uses outlining and thus suffer from the same issue.

**Comment by matmiranda** [comment]
@madskristensen Will you solve with the new update? I like your extension !

**Comment by cqpaul** [comment]
Visual Studio, Its original this function for JS, also face this problem!!
