### ISSUE TITLE
Region requires two clicks to expand

### ISSUE THREAD

**Issue by jamesgurung** [madskristensen/JavaScriptRegions#5]
### Installed product versions
- Visual Studio: 15.9 Preview 4
- This extension: 1.1.3

### Description
When a collapsed region has additional code below it, clicking on the + icon (or double clicking the region name) adds spaces around the region title but does not expand it. The icon must be clicked a second time to expand the region.

### Steps to recreate
1. Create a new Javascript file.
2. Add the code:
```
// #region Test
// #endregion
var a;
```
3. Collapse and expand the region.

### Current behavior
```
[+] [Test]
    var a;
```
to
```
[+] [ Test ]
    var a;
```
to
```
[-] // #region Test
    // #endregion
    var a;
```

### Expected behavior
```
[+] [Test]
    var a;
```
to
```
[-] // #region Test
    // #endregion
    var a;
```

**Comment by kp-xcess** [comment]
If you remove the space between '#region' and 'Test', expanding works as expected, thus within only one click. So there's at least that, as a workaround.
